name: Node.js CI

on:
  push:
    branches: [ "gh-pages", "main" ]
  pull_request:
    branches: [ "gh-pages", "main" ]

jobs:
  run_main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Installing dependencies
      run: |
         chmod +x predeploy.sh
         ls
         sh predeploy.sh
      shell: bash
